### ISSUE TITLE
MQTT Topic

### ISSUE THREAD

**Issue by GianCann** [BensonHsu/SBrick-Framework#2]
Hi,

it's possibile to use this lbrary directly with MQTT comand through topic?
For example:

//activate the motor connected to channel 1, at 100% speed
cmdn/identifier_of_sbrick_module/channel1/goforward 100

//stop the motor connected to channel 1
cmdn/identifier_of_sbrick_module/channel1/stop

//active the motor, in inverted rotation, at 50% of the speed
cmdn/identifier_of_sbrick_module/channel1/gorewind 50

**Comment by BensonHsu** [comment]
Yes, you can use MQTT message to control SBrick. The MQTT format of "drive" and "stop" are shown below respectively:
**[drive]**
_topic_: **sbrick/01/sp/drive**
_payload_: JSON format as below:
```json
{
    "sbrick_id": "string. SBrick ID. <sbrick MAC>",
    "channel": " string. hex string. the LEGO power function port you want to drive. <00|01|02|03>",
    "direction": "string. clockwise or counterclockwise. <00|01>",
    "power": "string. hex string. FF means 100% speed. <00~FF>",
    "exec_time": "number. seconds. 5566 means forever."
}
```
**[stop]**
_topic_: **sbrick/01/sp/stop**
_payload_: JSON format as below:
```json
{
    "sbrick_id": "string. Sbrick ID. <sbrick MAC>",
    "channels": "string list. channel list to stop. [00, 01]"
}
```
This means you can use any programming language to control SBrick, if you follow up with the above MQTT format.
